### ISSUE TITLE
Error fetching stats.

### ISSUE THREAD

**Issue by ooskay** [amcolash/MMM-json-feed#11] opened 2018-07-30 13:15 UTC
Hi There,
having issue..
my configs are below..

{
    module: 'MMM-json-feed',
    position: 'bottom_bar',
    config: {
     urls: [
        'http://88.248.2.178/onur/currency.php',
     ]
    }
 },

please see json output in below link.
http://88.248.2.178/onur/currency.php

any idea how can i able to solve?

**Comment by amcolash** [comment] 2018-08-16 06:41
I have been busy for a while now. This is a dupe of #10, issue has now been fixed. Closing and see resolution there.

**Closed as completed by amcolash** 2018-08-16 06:41 UTC
Labels: duplicate
